{% set name = "bacgwasim" %}
{% set version = "2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Morteza-M-Saber/BacGWASim/archive/refs/tags/v2.1.tar.gz
  sha256: 0e4ab5490f268048ce9d66fd4d940f3502e548323aebdd8f3bf8de34e3de8bc1

build:
  number: 0
  noarch: python
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt 

requirements:
  host:
    - python>=3
    - setuptools
  run:
    - python>=3
    - numpy
    - pandas
    - pyvcf
    - snakemake
    - bcftools==1.10.2
    - plink
    - gcta
    - snp-sites
    - openjdk=8|10
    - haploview
    - simbac
    - ete3

test:
  commands:
    - BacGWASim -h | grep "show this"

about:
  home: https://github.com/Morteza-M-Saber/BacGWASim
  license: MIT
  summary: |
    BacGWASim is a simulator for Bacterial Machine learning and Genome-wide Association studies.
extra:
  identifiers:
    - doi:10.1093/bioinformatics/bth457 
  container:
    extended-base: true
