{% set name = "hcgb" %}
{% set version = "0.3.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 5e78715e2b8e9e871fb7dcd0fbed32a612d3c0c7af99536a4e64d82157226ea3

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - biopython
    - filehash
    - pandas
    - patool
    - pip
    - python
    - termcolor
    - wget
    - xlsxwriter
  run:
    - biopython
    - filehash
    - pandas
    - patool
    - python
    - termcolor
    - wget
    - xlsxwriter

test:
  imports:
    - HCGB
    - HCGB.config
    - HCGB.functions
    - HCGB.sampleParser

about:
  home: "https://github.com/HCGB-IGTP/HCGB_python_functions/"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Useful python functions"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - jfsanchezherrero
