{% set name = "chia-rep" %}
{% set version = "3.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/c/chia-rep/ChIA-Rep-{{ version }}.tar.gz"
  sha256: 3366b45e9fded29d16d8bcdee46506a2fcc391725d1fe4460fdb868056863271

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python >3
  run:
    - numpy >=1.17.0
    - prettytable >=0.7.2
    - pybedgraph >=0.5.40
    - python >3
    - scipy >=1.3.1

test:
  imports:
    - chia_rep

about:
  home: "https://github.com/c0ver/chia_rep"
  license: MIT
  license_family: MIT
  summary: "A package for measuring reproducibility of ChIA-PET data."

extra:
  recipe-maintainers:
    - c0ver
    - minji011
